version: "3.8"
services:
  cowagent:
    build:
      context: .
      dockerfile: docker/Dockerfile.latest
      args:
        USE_CN_MIRROR: "true"
    container_name: cowagent
    restart: always
    ports:
      - "9899:9899"
    volumes:
      - ./config.json:/app/config.json
      - cow_data:/app/data
      - cow_workspace:/home/agent/cow

volumes:
  cow_data:
  cow_workspace:
